# Generated by Django 6.0 on 2026-01-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(default='fas fa-code', help_text="Enter FontAwesome class like 'fas fa-laptop-code'", max_length=100),
        ),
    ]
