# Generated by Django 6.0 on 2026-01-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_technology'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technology',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='technology',
            name='image',
            field=models.ImageField(default='temp.jpg', help_text='Upload a logo image (PNG/SVG)', upload_to='tech_logos/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('Frontend', 'Frontend'), ('Backend', 'Backend'), ('Database', 'Database'), ('Cloud Platform', 'Cloud Platform')], max_length=100),
        ),
    ]
