# Generated by Django 6.0 on 2026-01-06 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_technology_icon_class_technology_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon_class',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a logo or icon image (PNG/SVG recommended)', null=True, upload_to='core/images/icons/'),
        ),
        migrations.AlterField(
            model_name='technology',
            name='category',
            field=models.CharField(choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('Database', 'Database'), ('Cloud Platform', 'Cloud Platform')], max_length=100),
        ),
        migrations.AlterField(
            model_name='technology',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tech_logos/'),
        ),
    ]
