# Generated by Django 6.0 on 2026-01-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_service_icon_class_service_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='skill_1_desc',
            field=models.TextField(default='Description 1'),
        ),
        migrations.AddField(
            model_name='service',
            name='skill_1_title',
            field=models.CharField(default='Skill 1', max_length=100),
        ),
    ]
