# Generated by Django 6.0 on 2026-01-09 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_service_skill_1_desc_service_skill_1_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='skill_1_desc',
        ),
        migrations.RemoveField(
            model_name='service',
            name='skill_1_title',
        ),
    ]
