# Generated by Django 6.0 on 2026-06-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='service',
            field=models.CharField(blank=True, choices=[('Web Development', 'Web Development'), ('App Development', 'App Development'), ('SEO', 'SEO'), ('UI/UX', 'UI/UX')], max_length=100),
        ),
    ]
